builders:
  vm_generator:
    import: 'package:vm_generator/vm_generator.dart'
    builder_factories: ['vmBuilderFactory']
    build_extensions: {'.dart': ['.gvm.dart']}
    auto_apply: root_package
    build_to: source
targets:
  $default:
    builders:
      vm_generator:
        enabled: true
        generate_for:
          include:
            - lib/**/*_vm.dart